from django.contrib import admin
from .models import Müraciət, Əlaqə, Qeydiyyat, Bootcamps, BootcampTipi, Təlimlər, Mətinlər, Sessiyalar, Nümayişlər, Sillabuslar, Təlimçilər, Müəllimlər, Məzunlar,FAQ
admin.site.register(Müraciət)
admin.site.register(Əlaqə)
admin.site.register(Qeydiyyat)
admin.site.register(Bootcamps)
admin.site.register(BootcampTipi)
admin.site.register(Təlimlər)
admin.site.register(Mətinlər)
admin.site.register(Sessiyalar)
admin.site.register(Nümayişlər)
admin.site.register(Sillabuslar)
admin.site.register(Təlimçilər)
admin.site.register(Müəllimlər)
admin.site.register(Məzunlar)
admin.site.register(FAQ)
