# Generated by Django 5.1.6 on 2025-02-17 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bootcamps',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'main_bootcamps',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('question_en', models.TextField()),
                ('answer_en', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Müraciət',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Müəllimlər',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('work_position', models.CharField(max_length=100)),
                ('work_location', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='trainers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mətinlər',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=100)),
                ('description', models.TextField()),
                ('information', models.TextField()),
                ('money', models.IntegerField()),
                ('image', models.ImageField(upload_to='mətinlər/')),
                ('for_who', models.TextField()),
                ('certificates', models.TextField()),
                ('certificate_image', models.ImageField(upload_to='certificates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Məzunlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('work_position', models.CharField(max_length=100)),
                ('work_location', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='trainers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Qeydiyyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('event_date', models.DateField(blank=True, help_text='Etkinlik tarihini seçin', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Əlaqə',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('Data Science Bootcamp', 'Data Science Bootcamp'), ('SPSS Modeler Bootcamp', 'SPSS Modeler Bootcamp'), ('Kredit-Risk Analitikası', 'Kredit-Risk Analitikası'), ('Korporativ Təlimlər', 'Korporativ Təlimlər'), ('Data ilə əlaqəli işçi axtarırsınız', 'Data ilə əlaqəli işçi axtarırsınız'), ('Ödənişli proyekt köməyi', 'Ödənişli proyekt köməyi'), ('Ödənişsiz proyekt köməyi', 'Ödənişsiz proyekt köməyi')], default='Data Science Bootcamp', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BootcampTipi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bootcamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bootcamp_tipi', to='main.bootcamps')),
            ],
        ),
        migrations.CreateModel(
            name='Nümayişlər',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('info', models.TextField()),
                ('link', models.TextField()),
                ('trainer', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metinler', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nümayislər', to='main.mətinlər')),
            ],
        ),
        migrations.CreateModel(
            name='Sessiyalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_number', models.IntegerField()),
                ('date', models.DateField()),
                ('hour', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metinler', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sessiyalar', to='main.mətinlər')),
            ],
        ),
        migrations.CreateModel(
            name='Sillabuslar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('label', models.CharField(max_length=100, null=True)),
                ('information', models.TextField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metinler', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='syllabus', to='main.mətinlər')),
            ],
        ),
        migrations.CreateModel(
            name='Təlimlər',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(unique=True)),
                ('title', models.TextField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bootcamp_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telimler', to='main.bootcamptipi')),
            ],
        ),
        migrations.AddField(
            model_name='mətinlər',
            name='trainings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metinler', to='main.təlimlər'),
        ),
        migrations.CreateModel(
            name='Təlimçilər',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('work_location', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='trainers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metinler', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trainers', to='main.mətinlər')),
            ],
        ),
    ]
