# Generated by Django 5.1.6 on 2025-02-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='təlimlər',
            old_name='bootcamp_type',
            new_name='bootcamp_tipi',
        ),
        migrations.AlterField(
            model_name='bootcamps',
            name='order',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bootcamptipi',
            name='order',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='təlimlər',
            name='order',
            field=models.IntegerField(),
        ),
    ]
